/**
 * The aggregate counts and the coverage report.
 *
 * Ported from `report.py` of the code-docs skill. The report states its own denominator and its own
 * provenance. A coverage number without the population that it was measured over cannot be audited.
 */
import { join } from "node:path";
import { toJson, writeReport } from "../io.ts";
import { type DocSymbol, type FileReport, isParsed, type Stats } from "./model.ts";

/**
 * The percentage `100 * part / whole` with one decimal, as Python `round(x, 1)` gives it. Both
 * languages round the exact binary value, so they agree except on an exact tie. `toFixed` takes
 * the larger neighbour on a tie, and Python takes the even one. A tie in binary is a value of the
 * form odd/4 (6.25, 18.75), so the code finds it with one multiplication. An empty whole gives 100.
 */
export function percent(part: number, whole: number): number {
  if (whole === 0) return 100;
  const x = (100 * part) / whole;
  const quarters = x * 4;
  if (Number.isInteger(quarters) && quarters % 2 !== 0) {
    const floor = Math.floor(x * 10);
    return (floor % 2 === 0 ? floor : floor + 1) / 10;
  }
  return Number(x.toFixed(1));
}

/**
 * Returns the aggregate counts. `filesUnparsed` is separate and never counted as clean: an unparsed
 * file is an unknown, and an unknown that counts as clean is an all-clear that nothing earned.
 */
export function summarise(reports: FileReport[]): Stats {
  const parsed = reports.filter(isParsed);
  const symbols = parsed.flatMap((r) => r.symbols);
  const exported = symbols.filter((s) => s.exported);
  const documented = exported.filter((s) => s.hasDoc);
  const issues = symbols.flatMap((s) => s.issues);
  return {
    filesScanned: reports.length,
    filesParsed: parsed.length,
    filesUnparsed: reports.length - parsed.length,
    symbols: symbols.length,
    exportedSymbols: exported.length,
    exportedDocumented: documented.length,
    exportedDocumentedPct: percent(documented.length, exported.length),
    mustIssues: issues.filter((i) => i.tier === "MUST").length,
    shouldIssues: issues.filter((i) => i.tier === "SHOULD").length,
    filesMixedDialect: parsed.filter((r) => r.dialects.size > 1).length,
  };
}

/** The maximum number of rows in the MUST table. */
const TABLE_LIMIT = 200;

/** A percentage as text: one decimal, as `66.7` or `100.0`. */
export const pctText = (pct: number): string => pct.toFixed(1);

/** Returns the Markdown report, with a `## Verification` block that `check` re-derives. */
export function renderMarkdown(
  reports: FileReport[],
  stats: Stats,
  provenance: string,
  rootName: string,
): string {
  const lines = [
    "# Code documentation coverage",
    "",
    `**Repo:** \`${rootName}\``,
    "",
    "Generated by `repo-tools docs scan`. The rules are in the README of `repo-tools`.",
    "",
    "## Summary",
    "",
    "| Metric | Value |",
    "|---|---:|",
    `| Files scanned | ${stats.filesScanned} |`,
    `| Files parsed | ${stats.filesParsed} |`,
    `| **Files UNPARSED** (unknown, not clean) | **${stats.filesUnparsed}** |`,
    `| Symbols found | ${stats.symbols} |`,
    `| Exported symbols | ${stats.exportedSymbols} |`,
    `| Exported documented | ${stats.exportedDocumented} |`,
    `| Exported documented % | ${pctText(stats.exportedDocumentedPct)} |`,
    `| MUST issues (gated) | ${stats.mustIssues} |`,
    `| SHOULD issues (advisory) | ${stats.shouldIssues} |`,
    `| Files with mixed dialect | ${stats.filesMixedDialect} |`,
    "",
    "> The percentage is over **exported** symbols only. Private helpers are not",
    "> gated -- the public surface is a contract, internals are judgement.",
    "",
  ];
  const mustRows = reports
    .filter(isParsed)
    .flatMap((r) => r.symbols.flatMap((s) => s.issues.map((i) => ({ s, i }))))
    .filter(({ i }) => i.tier === "MUST");
  if (mustRows.length > 0) {
    lines.push(
      "## MUST issues",
      "",
      "| File | Line | Symbol | Rule | Detail |",
      "|---|---:|---|---|---|",
    );
    for (const { s, i } of mustRows.slice(0, TABLE_LIMIT)) {
      lines.push(`| \`${s.file}\` | ${s.line} | \`${s.name}\` | ${i.rule} | ${i.detail} |`);
    }
    if (mustRows.length > TABLE_LIMIT) {
      lines.push(
        `| … | | | | **${mustRows.length - TABLE_LIMIT} more not shown -- this table is TRUNCATED** |`,
      );
    }
    lines.push("");
  }
  const unparsed = reports.filter((r) => !isParsed(r));
  if (unparsed.length > 0) {
    lines.push(
      "## Unparsed files",
      "",
      "These were NOT measured. They are unknown, not clean.",
      "",
    );
    for (const r of unparsed) lines.push(`- \`${r.path}\` -- ${r.error}`);
    lines.push("");
  }
  lines.push(
    "## Verification",
    "",
    `- files_scanned: ${stats.filesScanned}`,
    `- files_parsed: ${stats.filesParsed}`,
    `- files_unparsed: ${stats.filesUnparsed}`,
    `- exported_symbols: ${stats.exportedSymbols}`,
    `- exported_documented: ${stats.exportedDocumented}`,
    `- must_issues: ${stats.mustIssues}`,
    `- discovery: ${provenance}`,
    "",
    "Run `repo-tools docs check .` to gate the repository. The command measures the code again and",
    "exits 1 on a MUST issue or on an unparsed file. It does not read this file.",
    "",
  );
  return lines.join("\n");
}

/** The keys of `coverage.json` are the snake_case keys of the Python tool, so its readers still work. */
function statsJson(stats: Stats): Record<string, number> {
  return {
    files_scanned: stats.filesScanned,
    files_parsed: stats.filesParsed,
    files_unparsed: stats.filesUnparsed,
    symbols: stats.symbols,
    exported_symbols: stats.exportedSymbols,
    exported_documented: stats.exportedDocumented,
    exported_documented_pct: stats.exportedDocumentedPct,
    must_issues: stats.mustIssues,
    should_issues: stats.shouldIssues,
    files_mixed_dialect: stats.filesMixedDialect,
  };
}

function symbolJson(s: DocSymbol): Record<string, unknown> {
  return {
    file: s.file,
    line: s.line,
    name: s.name,
    kind: s.kind,
    exported: s.exported,
    has_doc: s.hasDoc,
    params: s.params,
    doc_params: s.docParams,
    summary: s.summary,
    dialect: s.dialect,
    issues: s.issues,
  };
}

/** Writes `COVERAGE.md` and `coverage.json` into `outDir`, and returns both paths. */
export function writeOutputs(
  outDir: string,
  reports: FileReport[],
  stats: Stats,
  provenance: string,
  rootName: string,
): { markdown: string; json: string } {
  const markdown = join(outDir, "COVERAGE.md");
  const json = join(outDir, "coverage.json");
  writeReport(markdown, renderMarkdown(reports, stats, provenance, rootName));
  const payload = {
    summary: statsJson(stats),
    provenance,
    files: reports.map((r) => ({
      path: r.path,
      language: r.language,
      error: r.error,
      dialects: [...r.dialects].sort(),
      symbols: r.symbols.map(symbolJson),
    })),
  };
  writeReport(json, toJson(payload));
  return { markdown, json };
}
